### ISSUE TITLE
MIB Management: Uncaught ErrorException

### ISSUE THREAD

**Issue by juh** [patrickpr/trapdirector#3]
When clicking on "Status & Mibs" -> "MIB Management" I get the following exception:

```
Uncaught ErrorException: Illegal string offset 'attribs' in /usr/share/php/Icinga/Web/Form.php:248
Stack trace:
#0 /usr/share/php/Icinga/Web/Form.php(248): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Illegal string ...', '/usr/share/php/...', 248, Array)
#1 /usr/share/icingaweb2/modules/trapdirector/application/controllers/StatusController.php(264): Icinga\Web\Form->__construct('upload-form', Array)
#2 /usr/share/icingaweb2/modules/trapdirector/application/controllers/StatusController.php(200): Icinga\Module\Trapdirector\Controllers\UploadForm->__construct('upload-form')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Trapdirector\Controllers\StatusController->mibAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('mibAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Respons

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```
**My Environment:**
* trapdirector version 0.9.1:
* Icinga Web 2 version and modules 2.7.1:
* Icinga 2 version 2.10.5-1:
* Operating System and version: CentOS 7.6.1810
* Webserver, PHP versions: Apache 2.4.6, PHP 7.1.8

**Comment by patrickpr** [comment]
Hi,
It' a bug in the module that became an error with IcingaWeb2 version 2.7.1.

Replace the  /usr/share/icingaweb2/modules/trapdirector/application/controllers/StatusController.php file with the latest one : https://github.com/patrickpr/trapdirector/blob/master/application/controllers/StatusController.php
and let me know if it's working as expected.

**Comment by juh** [comment]
Thanks a lot, this works!
